fos_oauth_server:
    db_driver: orm

    client_class:        App\OAuthBundle\Entity\Client
    access_token_class:  App\OAuthBundle\Entity\AccessToken
    refresh_token_class: App\OAuthBundle\Entity\RefreshToken
    auth_code_class:     App\OAuthBundle\Entity\AuthCode

    service:
        user_provider: fos_user.user_provider.username
        options:
            access_token_lifetime: 86400
            refresh_token_lifetime: 1209600
            auth_code_lifetime: 30
